name: Github actions practice

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Get Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Install Dependencies
        run: mvn clean

      - name: Run Tests
        run: mvn test

  build:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Get Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Install Dependencies
        run: mvn clean

      - name: Prepare build
        run: mvn clean install -Dproject.build.sourceDirectory=com.example

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name:  Deploy
        run: echo "Deploy on production..."